### ISSUE TITLE
TipImage crash related to modApiExt

### ISSUE THREAD

**Issue by Lemonymous** [kartoFlane/ITB-ModUtils#4]
The game will crash with `error: EXCEPTION_ACCESS_VIOLATION` when viewing certain tipimages.
The cause appears erratic.

Some examples:
Tipimage with `CustomPawn = "Jelly_Lava1"`
Tipimage which deals damage to `Point(0,0)`

Commenting out line 418 (`d:SetCustomAnim("kf_ModApiExt_TipMarker")`) in `alter.lua`, appears to alleviate the issue.
This line appears to be related to being able to tell whether the tipimage is visible or not.

While I am not sure how important this detection is, I can propose an alternative solution using Skill.GetTipDamage, which allows you to detect when tipimages become visible/hidden. An example of how this is done can be found in one of my mods: `RF1995/scipts/WeaponHover.lua`.

The way I have set it up is that I register each weapon I want to track separately, but I am thinking that it might be an idea to add this functionality to the _mod loader_ itself, and add onTipImageHoveredHook and onTipImageUnHoveredHook for everyone to use.

I don't know the full use of the code that is causing issues in modApiExt, so anything you can add would be helpful.

**Comment by kartoFlane** [comment]
Thanks - I found the same things in my testing before I noticed you've created an issue for this... Seems like the game really doesn't like dealing damage to pawns that have animations with images outside of the `/units` directory...

This hook isn't really that important, and it's not used in modApiExt (I considered removing it altogether). Replacing the hacky custom anim-based implementation with your approach is definitely a good idea.
