### ISSUE TITLE
Potential to make this repository an extension for the mod loader

### ISSUE THREAD

**Issue by Lemonymous** [kartoFlane/ITB-ModUtils#9]
With https://github.com/itb-community/ITB-ModLoader/commit/7876ff1170f8000571d2833ae725c62f5bdefce4, the mod loader will support extensions.

An extension is for the most part just a mod, like any other, and can be enabled independently in the mod configuration menu or requested enabled by another mod.

I did a test where I added modApiExt as an extension with the following added init file to make it loadable like a mod if the repo is added as a submodule:
`ITB_ModUtils-master/scripts/init.lua`
```lua
local function init(self)
	modApiExt = require(self.resourcePath.."modApiExt/modApiExt"):init()
end

local function load(self, options, version)
	modApiExt:load(self, options, version)
end

return {
	id = "modApiExt",
	name = "Modding Utilities",
	version = "1.2",
	modApiVersion = "2.7.3",
	gameVersion = "1.2.83",
	isExtension = true,
	init = init,
	load = load
}
```

Test Mod requesting `modApiExt` and testing its hooks.
[RequestModApiExt.zip](https://github.com/itb-community/ITB-ModUtils/files/9893844/RequestModApiExt.zip)

It seems to be working on my end, though I have not tested what will happen if other mods still use modApiExt as a library.

**Comment by NamesAreHard6600** [comment]
I believe this and #5 can be closed, since it has already been done.
